const fs = require("fs");
const path = require("path");

const OUT = path.join(__dirname, "..", "src", "gateway", "routing", "wordfreq_seed.rs");
const SEED_VERSION = 1;

// High-frequency common words per language. OOV tokens in WordFreq => freq 0 => rare.
const EN = `the be to of and a in that have i it for not on with he as you do at this but his by from they we say her she or an will my one all would there their what so up out if about who get which go me when make can like time no just him know take people into year your good some could them see other than then now look only come its over think also back after use use two how our work first well way even new want because any these give day most us hello weather today thanks goodbye please help yes chat continue explain introduce morning evening afternoon howdy hi hey thank okay sure fine talk about what who mean doing nice great sorry could would should might may maybe perhaps probably world later see very much many still every find long where why while place right left hand old young small large big high low same different last next early late often always never again once here home away near far open close start stop run walk read write listen speak learn teach study play eat drink sleep live die love hate happy sad angry afraid tired hungry thirsty hot cold warm cool sunny rainy cloudy windy snow wind rain sun moon star sky earth sea river mountain city town country world life death birth child baby boy girl man woman friend family father mother brother sister son daughter husband wife parent student teacher doctor nurse police worker farmer driver cook waiter writer artist music song dance movie book story news paper letter email phone computer internet website app program code data file folder document page line word sentence question answer idea plan project task job money price cost pay buy sell shop store market food water milk bread rice meat fish fruit vegetable color red blue green yellow black white brown gray orange purple pink today tomorrow yesterday tonight week month year spring summer autumn winter monday tuesday wednesday thursday friday saturday sunday january february march april may june july august september october november december number zero one two three four five six seven eight nine ten hundred thousand million billion percent half quarter double triple`.split(/\s+/);

const ZH = `的 了 是 在 我 有 和 就 不 人 都 一 一个 上 也 很 到 说 要 去 你 会 着 没有 看 好 自己 这 那 他 她 它 我们 你们 他们 今天 明天 昨天 现在 时候 时间 天气 怎么样 你好 您好 谢谢 感谢 再见 可以 吗 呢 吧 啊 什么 怎么 为什么 哪里 谁 多少 几个 一些 这个 那个 这里 那里 然后 因为 所以 但是 如果 虽然 已经 还是 或者 以及 关于 介绍 解释 继续 还有 聊天 说说 聊聊 笑话 早上 晚上 中午 下午 几点 星期 月份 年份 吃饭 睡觉 工作 学习 学校 公司 朋友 家人 孩子 男人 女人 东西 事情 问题 回答 知道 觉得 认为 希望 需要 应该 可能 大概 也许 或者 非常 特别 真的 确实 当然 一起 一直 一下 一点 一定 一样 一般 经常 有时 从来 总是 开始 结束 完成 进行 使用 帮助 告诉 请问 您好 早上好 晚上好 在吗 可以吗 没问题 好的 嗯 行 好吧 多谢 辛苦 拜拜 回见`.split(/\s+/);

const JA = `の に は を た が で て と し れ さ ある いる も する から な こと として い や れる ない この ため その あっ よう また もの という あり まで られ なる へ か だ これ によって により おり より による ず なり られる において ば なかっ なく しかし について せ だっ その後 できる それ う なお のみ でき き つ における および いう さらに でも ら たり その他 に関する たち ます ん なに なん どう 今日 明日 昨日 天気 こんにちは おはよう こんばんは ありがとう さようなら 大丈夫 はい いいえ 教えて 説明 続けて 雑談 話そう 時間 何時 元気 です ます ください ございます そう ちょっと もう まだ よく とても 本当 多分 たぶん おそらく かもしれない`.split(/\s+/);

const KO = `의 가 이 은 는 을 를 에 에서 와 과 도 로 으로 로서 만 에게 한테 께서 그 저 이것 저것 그것 우리 너희 그들 여기 거기 어디 누구 무엇 어떻게 왜 언제 오늘 내일 어제 지금 시간 날씨 안녕 안녕하세요 감사 고마워 고맙습니다 안녕히 잘 가요 네 아니요 예 아니 알려줘 설명 계속 수다 잡담 이야기 몇 시 좋아 괜찮 문제 없음 그래 알겠어요 합니다 입니다 있어요 없어요 해요 가요 와요 봐요 말해요 생각해요 알아요 모르겠어요 아마 아마도 어쩌면 대략 정말 너무 매우 조금 많이 항상 가끔 자주 절대`.split(/\s+/);

function buildEntries(lang, words) {
  const seen = new Set();
  const entries = [];
  let w = 1000;
  for (const word of words) {
    const t = word.trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    entries.push({ lang, word: t, weight: w });
    w = Math.max(1, Math.floor(w * 0.92));
  }
  return entries;
}

function escapeRust(s) {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

const all = [
  ...buildEntries("en", EN),
  ...buildEntries("zh", ZH),
  ...buildEntries("ja", JA),
  ...buildEntries("ko", KO),
];

const lines = all.map(
  (e) => `    SeedWord { lang: "${e.lang}", word: "${escapeRust(e.word)}", weight: ${e.weight} },`
);

const rust = `// @generated by scripts/gen_wordfreq_tables.js — do not edit by hand

pub const SEED_VERSION: i32 = ${SEED_VERSION};

pub struct SeedWord {
    pub lang: &'static str,
    pub word: &'static str,
    pub weight: u32,
}

pub static SEED_WORDS: &[SeedWord] = &[
${lines.join("\n")}
];
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, rust, "utf8");
console.log(`wordfreq_seed.rs: ${all.length} words`);
